#!/usr/bin/env bash

set -e
set -u

DISTRO_ID=$(grep '^ID' /etc/os-release | cut -d '=' -f2)

flatpak_basic () {
    flatpak install com.github.ryonakano.pinit io.github.flattool.Warehouse com.github.tchx84.Flatseal org.onlyoffice.desktopeditors org.localsend.localsend_app org.freefilesync.FreeFileSync ca.desrt.dconf-editor -y
}

case "$DISTRO_ID" in
arch)
    sudo pacman -S --noconfirm gwenview timeshift strawberry firefox kolourpaint libreoffice-fresh gnome-disk-utility filelight keepassxc okular kalk kamoso gnome-system-monitor kdeconnect spectacle kclock kjournald khelpcenter

    # for kdeconnect
    sudo ufw allow 1716:1764/udp
    sudo ufw allow 1716:1764/tcp

    # for noobs so they don't have to touch the terminal
    if command -v paru &> /dev/null; then
        paru -S octopi alpm_octopi_utils
    fi

    flatpak_basic 
    ;;
esac

