#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

set -euo pipefail

DISTRO_ID=$(grep '^ID' /etc/os-release | cut -d '=' -f2)

flatpak_basic() {
    flatpak install com.github.ryonakano.pinit io.github.flattool.Warehouse \
        com.github.tchx84.Flatseal org.localsend.localsend_app \
        org.freefilesync.FreeFileSync ca.desrt.dconf-editor -y

    # NOTE: installing both flatpak-kcm and flatseal seems redundant,
    # but currently you can't set global setting for apps in flatpak-kcm.
    # That seems flatseal is the way to go, but I like how flatpak-kcm
    # integrates well with the system-settings.
}

case "$DISTRO_ID" in
arch)
    # this makes GTK apps listen to portal settings, like using Dolphin for filepicker,
    # using KDE font settings, etc.
    bash -c 'echo GTK_USE_PORTAL=1 >> /etc/environment'

    # GTK has rendering problem in low-end computers as it uses Vulkan now
    printf "Do you want to use OpenGL for rendering GTK apps? (RECOMMENDED)\nYou can always turn it off by deleting GSK_RENDERER=gl in /etc/environment.\nAnswer (y/N): "

    read -t 10 glopt
    if [[ $glopt == y ]]; then
        bash -c 'echo GSK_RENDERER=gl >> /etc/environment'
    fi

    unset glopt

    # for noobs so they don't have to touch the terminal
    pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    pacman-key --lsign-key 3056513887B78AEB
    pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
    pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

	bash -c "printf '[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist' >> /etc/pacman.conf"
	pacman -Syy --noconfirm pamac

    # NOTE: explanations for non-gui components that will be installed:
    # - kcron: task scheduler will be available in the system settings
    # - ffmpegthumbs: video thumbnails generator used by Dolphin
    # - power-profiles-daemon: power profiles will be available. especially useful for
    #     laptop
    # - xdg-desktop-portal-gtk: make your GTK apps listen to portal settings. GTK_USE_PORTAL=1
    #     must be set in /etc/environment
    # - flatpak-kcm: settings for flatpak apps will be availabe in the system settings
    # - krdc & krfb: both are useable with KDE connect for remote desktop
    pacman -S --noconfirm gwenview timeshift amberol firefox-developer-edition kolourpaint \
        libreoffice-fresh gnome-disk-utility filelight keepassxc okular kalk kamoso krecorder \
        gnome-system-monitor kdeconnect spectacle kclock kjournald khelpcenter pdfarranger \
        krdc krfb systemdgenie ffmpegthumbs xdg-desktop-portal-gtk power-profiles-daemon \
        kcron flatpak-kcm

    # for timeshift scheduler. I'm commenting it out for now as for some reason snapshots created by
    # the scheduler is corrupt and it once broke my system
    # systemctl enable --now cronie

    # for kdeconnect
    ufw allow 1716:1764/udp
    ufw allow 1716:1764/tcp


    flatpak_basic
    ;;
esac
