#!/usr/bin/env bash

stow . --no-folding

u=$(echo $USER)

if [ "$EUID" -ne 0 ]; then
  sudo "$0" "$@"
  exit $?
fi


DISTRO_ID=

if [ -z "$CUSTOM_BIN" ]; then
    export CUSTOM_BIN=/home/$u/.local/bin
fi

set -euo pipefail

mkdir -p $CUSTOM_BIN

echo "initializing basic components..."

# lf and fzf might be available in you package managers, but usually they are out of date
amd64_install() {
    #lf
    wget -O - https://github.com/gokcehan/lf/releases/latest/download/lf-linux-amd64.tar.gz | tar -xz -C $CUSTOM_BIN

    # fzf
    curl https://api.github.com/repos/junegunn/fzf/releases/latest | jq -r '.assets[3] | .browser_download_url' | xargs wget -O - | tar -xz -C $CUSTOM_BIN

    # this one is the official install script for fzf
    # git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    # ~/.fzf/install
}

if [ -d "/data/data/com.termux" ]; then
    DISTRO_ID=termux
else
    DISTRO_ID=$(grep '^ID' /etc/os-release | cut -d '=' -f2)
fi

case "$DISTRO_ID" in
termux)
    pkg install vim stow unzip grep fzf lf
    ;;
arch)
    # basic requirement is that you've already installed git (and flatpak, if you want to
    # install GUI softwares) beforehand
    pacman -S --noconfirm --needed ufw reflector
    systemctl enable --now ufw

    bash -c 'echo "--country SG" >> /etc/xdg/reflector/reflector.conf'
    sed -i 's/^--latest.*/--latest 10/' "/etc/xdg/reflector/reflector.conf"
    systemctl enable --now reflector.service reflector.timer

    pacman -S --noconfirm --needed stow btop ntfs-3g wl-clipboard rsync less man-db udftools exfatprogs dosfstools f2fs-tools vim zoxide unzip zsh tmux fzf lf system-config-printer fastfetch vnstat nethogs

    # gui for basic use. disk partitioning is much nicer in gui, other things covered by the terminal
    pacman -S --noconfirm --needed gnome-disk-utility gwenview okular mpv

    systemctl enable --now vnstat
    chsh -s $(which zsh) $u
    
    if ! command -v paru >> /dev/null; then
        curl https://api.github.com/repos/Morganamilo/paru/releases/latest | jq -r '.assets[2] | .browser_download_url' | xargs wget -O - | tar -x --zstd -C $CUSTOM_BIN
    fi

    unset u

    ;;

fedora)
    dnf install stow vim zoxide -y
    amd64_install

    ;;

ubuntu)
    apt install stow vim zoxide
    amd64_install

    ;;

linuxmint)
    apt update

    apt install stow vim zoxide btop zsh tmux nethogs vnstat

    amd64_install
    ;;
esac

if [ -f ../.bashrc ]; then
    if [ -f ../.bashrc.bak ]; then 
        rm -f ../bashrc.bak
    fi

	mv ../.bashrc ../.bashrc.bak
fi

# because I have it aliased to something else
unset stow


# source ~/.bashrc

echo "all basic components are successfully installed"
