#!/usr/bin/env bash

set -u
set -e

echo "initializing all development environment..."
DISTRO_ID=$(grep '^ID' /etc/os-release | cut -d '=' -f2)

# if [[ $DISTRO_ID == "fedora" ]]; then
# wget -O - https://github.com/go-task/task/releases/download/v3.39.2/task_linux_amd64.tar.gz | tar -xz -C $CUSTOM_BIN
# fi
#
case "$DISTRO_ID" in
arch)
    sudo pacman -S go go-task nodejs npm postgresql --noconfirm --needed
    go install github.com/a-h/templ/cmd/templ@latest

    paru -S vscodium-bin
    ;;
esac

echo "successfully initializing development environment"
