#!/usr/bin/env bash

# https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
get_script_dir() {
    local SOURCE_PATH="${BASH_SOURCE[0]}"
    local SYMLINK_DIR
    local SCRIPT_DIR
    # Resolve symlinks recursively
    while [ -L "$SOURCE_PATH" ]; do
        # Get symlink directory
        SYMLINK_DIR="$( cd -P "$( dirname "$SOURCE_PATH" )" >/dev/null 2>&1 && pwd )"
        # Resolve symlink target (relative or absolute)
        SOURCE_PATH="$(readlink "$SOURCE_PATH")"
        # Check if candidate path is relative or absolute
        if [[ $SOURCE_PATH != /* ]]; then
            # Candidate path is relative, resolve to full path
            SOURCE_PATH=$SYMLINK_DIR/$SOURCE_PATH
        fi
    done
    # Get final script directory path from fully resolved source path
    SCRIPT_DIR="$(cd -P "$( dirname "$SOURCE_PATH" )" >/dev/null 2>&1 && pwd)"
    echo "$SCRIPT_DIR"
}

export u=$([ -n "$1" ] && echo "$1" || echo "$USER")

DISTRO_ID=

export DISTRO_ID=$([ -d "/data/data/com.termux" ] && echo "termux" ||
    echo $(source /etc/os-release && echo $ID))

# NOTE: I tested this thing and the script should not run twice anymore.
# But if it still do then this is the culprit
if [ "$EUID" -ne 0 ]; then
    # you will need to discard all changes with git if you want to use all of the repo components
    dir_path="$(get_script_dir)"

    echo "dir path: $dir_path"

    stow --no-folding --adopt -v -t $HOME -d "$dir_path" .

    sudo "$0" "$u" "$@"
    exit $?
fi

if [ -f ../.bashrc ]; then
    if [ -f ../.bashrc.bak ]; then rm -f ../bashrc.bak; fi

    mv ../.bashrc ../.bashrc.bak
fi

read -p "Reminder: dont run manually with sudo as it will cause unexpected behavior, 
Are you sure want to continue? [y/N]: " cont

if [[ $cont != "y" ]]; then 
    echo 'operation aborted'
    exit 1
fi

if [ -z "$CUSTOM_BIN" ]; then
    export CUSTOM_BIN=/home/$u/.local/bin
fi

mkdir -p $CUSTOM_BIN

set -euo pipefail

make_zsh_default() {
    chsh -s $(which zsh) $u
}

arch_primary_install() {
    pacman -Syy --noconfirm --needed --disable-download-timeout ufw reflector grub-btrfs \
        inotify-tools stow btop ntfs-3g wl-clipboard rsync less man-db udftools \
        exfatprogs dosfstools f2fs-tools vim zoxide unzip zsh tmux fzf lf system-config-printer \
        fastfetch vnstat nethogs cryfs fwupd kio-admin ttf-ms-fonts power-profiles-daemon \
        pacman-contrib print-manager cups

    # gui for basic use. disk partitioning is much nicer in gui, other things covered by the terminal
    pacman -S --noconfirm --needed --disable-download-timeout gnome-disk-utility gwenview okular \
        mpv kalk kamoso krecorder spectacle btrfs-assistant kimageformats 

    systemctl enable --now ufw grub-btrfsd vnstat paccache.timer cups-socket
    ufw default deny
}

arch_add_reflector() {
    bash -c 'echo "--country SG" >> /etc/xdg/reflector/reflector.conf'
    sed -i 's/^--latest.*/--latest 10/' "/etc/xdg/reflector/reflector.conf"
    systemctl enable --now reflector.service reflector.timer
}

arch_add_chaotic_aur() {
    pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    pacman-key --lsign-key 3056513887B78AEB
    pacman -U --noconfirm --needed 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
    pacman -U --noconfirm --needed 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

    bash -c "printf '[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist' >> /etc/pacman.conf"
    pacman -Sy --noconfirm --needed --disable-download-timeout paru octopi
}

echo "initializing basic components..."

# lf and fzf might be available in you package managers, but usually they are out of date
amd64_install() {
    #lf
    wget -O - https://github.com/gokcehan/lf/releases/latest/download/lf-linux-amd64.tar.gz | tar -xz -C $CUSTOM_BIN

    # fzf
    curl https://api.github.com/repos/junegunn/fzf/releases/latest | jq -r '.assets[3] | .browser_download_url' | xargs wget -O - | tar -xz -C $CUSTOM_BIN

    # this one is the official install script for fzf
    # git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    # ~/.fzf/install
}

case "$DISTRO_ID" in
termux)
    pkg install vim stow unzip grep fzf lf
    ;;

arch)
    arch_primary_install
    arch_add_chaotic_aur
    arch_add_reflector
    make_zsh_default
    ;;

cachyos)
    arch_primary_install
    arch_add_chaotic_aur
    make_zsh_default

    ;;
fedora)
    dnf install -y vim zoxide btop wl-clipboard zsh fastfetch vnstat nethogs gnome-disk-utility \
        mpv trash-cli python3-shtab

    systemctl enable --now vnstat

    make_zsh_default
    amd64_install
    ;;

ubuntu)
    apt install stow vim zoxide
    amd64_install
    ;;

linuxmint)
    apt update

    apt install stow vim zoxide btop zsh tmux nethogs vnstat

    amd64_install
    ;;

alpine)
    echo "note: uncomment the community package in /etc/apk/repositories first"
    apk add vim bash bash-completion shadow ufw btop lf ncurses tmux stow curl zoxide \
        fzf fzf-tmux

    ufw default deny

    echo "remember to allow ports you need such as for ssh"

    ;;
esac

# source ~/.bashrc

echo "all basic components are successfully installed"
