#!/usr/bin/env bash

set -u

./init_basic

echo "initializing all components..."

amd64_install() {
    # oh-my-posh
    curl -s https://ohmyposh.dev/install.sh | bash -s -- -d $CUSTOM_BIN
}

case "$DISTRO_ID" in
termux)
    pkg install lsd jq lazygit neovim oh-my-posh git-delta
    ;;

fedora)
    sudo dnf copr enable atim/lazygit -y
    sudo dnf install lsd jq lazygit trash-cli neovim git-delta -y
    amd64_install
    ;;

ubuntu)
    sudo apt install lsd jq trash-cli neovim
    amd64_install

    # lazygit
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    sudo install lazygit $CUSTOM_BIN
    ;;

esac

echo "all components are successfully installed"
