#!/usr/bin/env bash


export DISTRO_ID=$([ -d "/data/data/com.termux" ] && echo "termux" ||
    echo $(source /etc/os-release && echo $ID))

set -euo pipefail

echo "initializing all development environment..."

echo $DISTRO_ID

# if [[ $DISTRO_ID == "fedora" ]]; then
# wget -O - https://github.com/go-task/task/releases/download/v3.39.2/task_linux_amd64.tar.gz | tar -xz -C $CUSTOM_BIN
# fi
#
case "$DISTRO_ID" in
arch)
    sudo pacman -S go nodejs npm postgresql --noconfirm --needed

    paru -S --needed vscodium-bin
    ;;
cachyos)
    sudo pacman -S go nodejs npm postgresql --noconfirm --needed

    paru -S --needed vscodium-bin
    ;;

termux)
    pkg install go postgresql memcached
    ;;

alpine)
    doas apk go postgresql memcached 

    doas rc-update add postgresql
    doas r-update add memcached
    doas rc-service postgresql start
    doas rc-service memcached start
    ;;

esac

echo "successfully initializing development environment"
