import = [
    "~/.config/alacritty/keybindings.toml",
]

[shell]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
opacity = 0.6

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "normal" }
size = 14

[colors]

    [colors.primary]
    background = "#000000"
