[keyboard]
bindings = [
	{ key = "PageUp", mods = "Control|Shift", action = "ScrollHalfPageUp" },
	{ key = "PageDown", mods = "Control|Shift", action = "ScrollHalfPageDown"},
	{ key = "ArrowUp", mods = "Control|Shift", action = "ScrollLineUp" },
	{ key = "ArrowDown", mods = "Control|Shift", action = "ScrollLineDown" },
	{ key = "Home", mods = "Control|Shift", action = "ScrollToTop" },
	{ key = "End", mods = "Control|Shift", action = "ScrollToBottom" },
]
